# Generated by Django 6.0.2 on 2026-02-08 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_latitude_branch_longitude'),
        ('communications', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(help_text='Email subject line with optional placeholders', max_length=300)),
                ('body', models.TextField(help_text='Email body with placeholders like {{university_name}}')),
                ('category', models.CharField(choices=[('ONBOARDING', 'Partner Onboarding'), ('INTAKE', 'Intake Reminder'), ('DOCUMENT', 'Document Request'), ('FOLLOW_UP', 'Application Follow-up'), ('MARKETING', 'Marketing Outreach'), ('CUSTOM', 'Custom Template')], default='CUSTOM', max_length=20)),
                ('placeholders', models.JSONField(blank=True, default=list, help_text='List of placeholder tokens available in this template')),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_branch', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['category', 'name'],
            },
        ),
    ]
