# Generated by Django 6.0.1 on 2026-02-04 17:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('students', '0001_initial'),
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university_name', models.CharField(blank=True, max_length=200, null=True)),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
                ('intake', models.CharField(help_text='e.g., September 2026', max_length=50)),
                ('application_type', models.CharField(choices=[('DIRECT', 'Direct Application'), ('UCAS', 'UCAS'), ('AGENT_PORTAL', 'Agent Portal')], default='DIRECT', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DOCUMENTS_READY', 'Documents Ready'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('CONDITIONAL_OFFER', 'Conditional Offer'), ('UNCONDITIONAL_OFFER', 'Unconditional Offer'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('OFFER_DECLINED', 'Offer Declined'), ('CAS_REQUESTED', 'CAS Requested'), ('CAS_RECEIVED', 'CAS Received'), ('ENROLLED', 'Enrolled'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='DRAFT', max_length=25)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('offer_type', models.CharField(blank=True, help_text='Conditional/Unconditional', max_length=20, null=True)),
                ('offer_conditions', models.JSONField(blank=True, default=list, help_text='List of conditions to be met')),
                ('conditions_met', models.BooleanField(default=False)),
                ('cas_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cas_issue_date', models.DateField(blank=True, null=True)),
                ('tuition_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_branch', to='branches.branch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='universities.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.student')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='universities.university')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('DOCUMENTS_READY', 'Documents Ready'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('CONDITIONAL_OFFER', 'Conditional Offer'), ('UNCONDITIONAL_OFFER', 'Unconditional Offer'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('OFFER_DECLINED', 'Offer Declined'), ('CAS_REQUESTED', 'CAS Requested'), ('CAS_RECEIVED', 'CAS Received'), ('ENROLLED', 'Enrolled'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], max_length=25, null=True)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('DOCUMENTS_READY', 'Documents Ready'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('CONDITIONAL_OFFER', 'Conditional Offer'), ('UNCONDITIONAL_OFFER', 'Unconditional Offer'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('OFFER_DECLINED', 'Offer Declined'), ('CAS_REQUESTED', 'CAS Requested'), ('CAS_RECEIVED', 'CAS Received'), ('ENROLLED', 'Enrolled'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], max_length=25)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Snapshot of changed fields')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='applications.application')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Status Log',
                'ordering': ['-changed_at'],
            },
        ),
    ]
