# Generated by Django 6.0.2 on 2026-02-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_applicationsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_ref',
            field=models.CharField(blank=True, help_text='e.g. BWBS-2026-001', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='application',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=2),
        ),
    ]
