# Generated by Django 6.0.2 on 2026-02-08 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_application_ref_application_priority'),
        ('branches', '0001_initial'),
        ('students', '0007_leadinteraction_audio_file_and_more'),
        ('universities', '0005_intakedate_partnershipagreement_universitycontact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Primary counselor/owner for this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='fit_score',
            field=models.PositiveIntegerField(default=0, help_text='Profile to university fit score (0-100)'),
        ),
        migrations.AddField(
            model_name='application',
            name='risk_score',
            field=models.PositiveIntegerField(default=0, help_text='Operational risk score (0-100)'),
        ),
        migrations.AddField(
            model_name='application',
            name='target_offer_date',
            field=models.DateField(blank=True, help_text='Target date for offer decision', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='target_cas_date',
            field=models.DateField(blank=True, help_text='Target date for CAS issuance', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='next_action_at',
            field=models.DateTimeField(blank=True, help_text='Next action follow-up time', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, help_text='Last activity timestamp for SLA tracking', null=True),
        ),
        migrations.CreateModel(
            name='ApplicationChecklistTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('PASSPORT', 'Passport'), ('NATIONAL_ID', 'National ID'), ('TRANSCRIPT', 'Academic Transcript'), ('CERTIFICATE', 'Certificate'), ('ENGLISH_TEST', 'English Test Score'), ('BANK_STATEMENT', 'Bank Statement'), ('SPONSOR_LETTER', 'Sponsor Letter'), ('SOP', 'Statement of Purpose'), ('CV', 'CV/Resume'), ('REFERENCE', 'Reference Letter'), ('OFFER_LETTER', 'Offer Letter'), ('CAS', 'CAS Document'), ('VISA', 'Visa Document'), ('OTHER', 'Other')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('due_days_offset', models.IntegerField(default=7, help_text='Days from application creation to due date')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(blank=True, help_text='Program level (e.g., Undergraduate)', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_branch', to='branches.branch')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_checklist_templates', to='universities.university')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('PASSPORT', 'Passport'), ('NATIONAL_ID', 'National ID'), ('TRANSCRIPT', 'Academic Transcript'), ('CERTIFICATE', 'Certificate'), ('ENGLISH_TEST', 'English Test Score'), ('BANK_STATEMENT', 'Bank Statement'), ('SPONSOR_LETTER', 'Sponsor Letter'), ('SOP', 'Statement of Purpose'), ('CV', 'CV/Resume'), ('REFERENCE', 'Reference Letter'), ('OFFER_LETTER', 'Offer Letter'), ('CAS', 'CAS Document'), ('VISA', 'Visa Document'), ('OTHER', 'Other')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('MISSING', 'Missing'), ('UPLOADED', 'Uploaded'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('WAIVED', 'Waived')], default='MISSING', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='applications.application')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_branch', to='branches.branch')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_checklist_items', to='students.document')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_items', to='applications.applicationchecklisttemplate')),
            ],
            options={
                'ordering': ['due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('visibility', models.CharField(choices=[('INTERNAL', 'Internal'), ('TEAM', 'Team')], default='INTERNAL', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='applications.application')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_branch', to='branches.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
