# Generated by Django 6.0.2 on 2026-02-08 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_assigned_to_application_fit_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationnote',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_notes', to='applications.application'),
        ),
    ]
