# Generated by Django 6.0.1 on 2026-02-04 17:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('requirements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(choices=[('WALK_IN', 'Walk-in'), ('WEBSITE', 'Website'), ('FACEBOOK', 'Facebook'), ('REFERRAL', 'Referral'), ('EVENT', 'Event'), ('OTHER', 'Other')], default='WALK_IN', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('CONVERTED', 'Converted'), ('LOST', 'Lost')], default='NEW', max_length=20)),
                ('intended_intake', models.CharField(blank=True, help_text='e.g., Sep 2026', max_length=50, null=True)),
                ('preferred_level', models.CharField(blank=True, help_text='Undergrad, Postgrad, PhD', max_length=50, null=True)),
                ('budget_range', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Counselor assigned to this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_branch', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('WALK_IN', 'Walk-in'), ('WEBSITE', 'Website'), ('FACEBOOK', 'Facebook'), ('REFERRAL', 'Referral'), ('EVENT', 'Event'), ('OTHER', 'Other')], default='WALK_IN', help_text='How this student was acquired', max_length=20)),
                ('student_code', models.CharField(help_text='Unique code, e.g., LHR-2026-00123', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('current_address', models.TextField(blank=True, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('academic_history', models.JSONField(blank=True, default=list, help_text='Array of qualifications: [{degree, institution, year, grade}]')),
                ('english_test_type', models.CharField(blank=True, help_text='IELTS, PTE, TOEFL, etc.', max_length=20, null=True)),
                ('english_test_score', models.JSONField(blank=True, default=dict, help_text='Detailed scores: {overall, reading, writing, speaking, listening}')),
                ('work_experience', models.JSONField(blank=True, default=list, help_text='Array of experiences: [{company, role, duration}]')),
                ('financial_status', models.JSONField(blank=True, default=dict, help_text='Sponsor details, bank info')),
                ('profile_completeness', models.PositiveIntegerField(default=0, help_text='Percentage of profile completion (0-100)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('ENROLLED', 'Enrolled'), ('WITHDRAWN', 'Withdrawn')], default='ACTIVE', max_length=20)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_branch', to='branches.branch')),
                ('counselor', models.ForeignKey(blank=True, help_text='Assigned counselor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(blank=True, help_text='Original lead if converted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_student', to='students.lead')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('PASSPORT', 'Passport'), ('NATIONAL_ID', 'National ID'), ('TRANSCRIPT', 'Academic Transcript'), ('CERTIFICATE', 'Certificate'), ('ENGLISH_TEST', 'English Test Score'), ('BANK_STATEMENT', 'Bank Statement'), ('SPONSOR_LETTER', 'Sponsor Letter'), ('SOP', 'Statement of Purpose'), ('CV', 'CV/Resume'), ('REFERENCE', 'Reference Letter'), ('OFFER_LETTER', 'Offer Letter'), ('CAS', 'CAS Document'), ('VISA', 'Visa Document'), ('OTHER', 'Other')], max_length=20)),
                ('document_type', models.CharField(help_text='Specific document name', max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='For passport, visa, etc.', null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_branch', to='branches.branch')),
                ('requirement', models.ForeignKey(blank=True, help_text='Linked to a specific visa requirement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_documents', to='requirements.requireddocument')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
