# Generated by Django 6.0.1 on 2026-02-06 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('students', '0002_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email'], name='idx_lead_email'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='idx_lead_status'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to'], name='idx_lead_assigned'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_code'], name='idx_student_code'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='idx_student_status'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['counselor'], name='idx_student_counselor'),
        ),
    ]
