# Generated by Django 6.0.2 on 2026-02-07 19:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('students', '0004_document_notify_before_days_documentalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_sla_violated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_interaction_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('HOT', 'Hot (High Interest) 🔥'), ('WARM', 'Warm (Medium Interest)'), ('COLD', 'Cold (Low Interest)')], default='WARM', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='score',
            field=models.IntegerField(default=0, help_text='Lead score based on interest/profile (0-100)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='target_country',
            field=models.CharField(blank=True, help_text='Destination of interest', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='LeadInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('CALL', 'Phone Call'), ('WHATSAPP', 'WhatsApp Message'), ('EMAIL', 'Email sent'), ('MEETING', 'In-person/Online Meeting'), ('NOTE', 'General Note')], default='NOTE', max_length=20)),
                ('content', models.TextField(help_text='Detailed summary of the conversation')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_branch', to='branches.branch')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='students.lead')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Interaction',
                'verbose_name_plural': 'Lead Interactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
