# Generated by Django 6.0.2 on 2026-02-07 19:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('students', '0005_lead_is_sla_violated_lead_last_interaction_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='win_probability',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='AI estimated conversion probability (0-100)', max_digits=5),
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('FOLLOW_UP', 'Follow up'), ('BROCHURE', 'Brochure/Info'), ('DOCUMENT_REQ', 'Document Request'), ('GREETING', 'Greeting'), ('OTHER', 'Other')], default='FOLLOW_UP', max_length=20)),
                ('content', models.TextField(help_text='Template content. Use {first_name}, {last_name}, {target_country} as placeholders.')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_branch', to='branches.branch')),
            ],
            options={
                'verbose_name': 'WhatsApp Template',
                'verbose_name_plural': 'WhatsApp Templates',
                'ordering': ['title'],
            },
        ),
    ]
