# Generated by Django 6.0.2 on 2026-02-08 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_assigned_to_application_fit_score_and_more'),
        ('students', '0007_leadinteraction_audio_file_and_more'),
        ('universities', '0004_scholarship'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='application',
            field=models.ForeignKey(blank=True, help_text='Optional application this document is linked to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='applications.application'),
        ),
        migrations.AddField(
            model_name='lead',
            name='suggested_universities',
            field=models.ManyToManyField(blank=True, help_text='AI-suggested universities based on lead profile', related_name='suggested_for_leads', to='universities.university'),
        ),
    ]
