# Generated by Django 6.0.1 on 2026-02-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_add_performance_indexes'),
        ('branches', '0001_initial'),
        ('finance', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionclaim',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='commissionclaim',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='feetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='feetype',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='commissionclaim',
            index=models.Index(fields=['branch', 'is_deleted'], name='commissionclaim_branch_active_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionclaim',
            index=models.Index(fields=['branch', 'created_at'], name='commissionclaim_branch_created_idx'),
        ),
        migrations.AddIndex(
            model_name='feetype',
            index=models.Index(fields=['branch', 'is_deleted'], name='feetype_branch_active_idx'),
        ),
        migrations.AddIndex(
            model_name='feetype',
            index=models.Index(fields=['branch', 'created_at'], name='feetype_branch_created_idx'),
        ),
    ]
