# Generated by Django 6.0.1 on 2026-02-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='commissionclaim',
            name='commissionclaim_branch_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='commissionclaim',
            name='commissionclaim_branch_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='feetype',
            name='feetype_branch_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='feetype',
            name='feetype_branch_created_idx',
        ),
    ]
