# Generated by Django 6.0.2 on 2026-02-06 20:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0004_application_application_ref_application_priority'),
        ('branches', '0001_initial'),
        ('students', '0004_document_notify_before_days_documentalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('CAS_RECEIVED', 'CAS Received'), ('DOCS_PREPARED', 'Documents Prepared'), ('IHS_PAID', 'IHS Paid'), ('VFS_SCHEDULED', 'VFS Appointment Scheduled'), ('BIOMETRICS_DONE', 'Biometrics Done'), ('VISA_SUBMITTED', 'Visa Submitted'), ('ADDITIONAL_DOCS', 'Additional Documents Requested'), ('VISA_APPROVED', 'Visa Approved'), ('VISA_REJECTED', 'Visa Rejected'), ('PASSPORT_COLLECTED', 'Passport Collected'), ('APPEAL', 'Under Appeal')], default='CAS_RECEIVED', max_length=20)),
                ('decision_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('vfs_date', models.DateTimeField(blank=True, help_text='VFS appointment date and time', null=True)),
                ('vfs_location', models.CharField(blank=True, max_length=200, null=True)),
                ('biometric_done', models.BooleanField(default=False)),
                ('tb_test_done', models.BooleanField(default=False)),
                ('tb_test_date', models.DateField(blank=True, null=True)),
                ('ihs_reference', models.CharField(blank=True, help_text='Immigration Health Surcharge reference', max_length=50, null=True)),
                ('ihs_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('visa_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('visa_start_date', models.DateField(blank=True, null=True)),
                ('visa_end_date', models.DateField(blank=True, null=True)),
                ('refusal_reason', models.TextField(blank=True, null=True)),
                ('appeal_submitted', models.BooleanField(default=False)),
                ('appeal_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visa_case', to='applications.application')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_branch', to='branches.branch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_cases', to='students.student')),
            ],
            options={
                'verbose_name': 'Visa Case',
                'verbose_name_plural': 'Visa Cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisaMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('CAS', 'CAS'), ('VISA', 'Visa'), ('IHS', 'IHS'), ('VFS', 'VFS'), ('BIOMETRICS', 'Biometrics'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('alerted_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_branch', to='branches.branch')),
                ('visa_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='visas.visacase')),
            ],
            options={
                'ordering': ['due_date'],
                'indexes': [models.Index(fields=['status'], name='idx_visa_milestone_status')],
            },
        ),
    ]
