# Generated by Django 6.0.2 on 2026-02-08 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, help_text='Total lifetime points earned')),
                ('xp', models.IntegerField(default=0, help_text='Experience points toward next level')),
                ('level', models.IntegerField(default=1)),
                ('total_conversions', models.IntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0, help_text='Unpaid commission balance', max_digits=12)),
                ('average_response_time', models.DurationField(blank=True, null=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Performance',
                'verbose_name_plural': 'Employee Performances',
            },
        ),
    ]
