# Generated by Django 6.0.2 on 2026-02-08 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employeeperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='GBP', max_length=10)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('contract_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('FIXED_TERM', 'Fixed Term'), ('PROBATION', 'Probationary'), ('CONTRACTOR', 'External Contractor')], default='PROBATION', max_length=20)),
                ('contract_progress', models.IntegerField(default=0, help_text='Progress percentage 0-100')),
                ('last_review_date', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Dossier',
                'verbose_name_plural': 'Employee Dossiers',
            },
        ),
    ]
