# Generated by Django 6.0.2 on 2026-02-08 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employeeauditlog_employeeincentive'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month for this payroll')),
                ('base_salary_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('incentive_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_payout', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_payout', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('VOID', 'Void')], default='PENDING', max_length=20)),
                ('payout_date', models.DateField(blank=True, null=True)),
                ('payslip_pdf', models.FileField(blank=True, null=True, upload_to='payslips/')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Payroll',
                'verbose_name_plural': 'Employee Payrolls',
                'unique_together': {('user', 'month')},
            },
        ),
    ]
