# Generated by Django 6.0.2 on 2026-02-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_latitude_branch_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='auto_handoff_enabled',
            field=models.BooleanField(default=False, help_text='Allow automatic lead handoffs after hours'),
        ),
        migrations.AddField(
            model_name='branch',
            name='closing_time',
            field=models.TimeField(default='18:00:00', help_text='Local closing time'),
        ),
        migrations.AddField(
            model_name='branch',
            name='opening_time',
            field=models.TimeField(default='09:00:00', help_text='Local opening time'),
        ),
    ]
