# Generated by Django 6.0.2 on 2026-02-09 19:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_branchcomplaint_fixedasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchAnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField(auto_now_add=True)),
                ('total_leads', models.IntegerField()),
                ('converted_leads', models.IntegerField()),
                ('conversion_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active_students', models.IntegerField()),
                ('total_revenue_estimate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_payroll_monthly', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pipeline_state', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bi_snapshots', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Branch Analytics Snapshot',
                'verbose_name_plural': 'Branch Analytics Snapshots',
                'ordering': ['-snapshot_date', 'branch'],
                'unique_together': {('branch', 'snapshot_date')},
            },
        ),
    ]
