# Generated by Django 6.0.2 on 2026-02-09 19:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_branchanalyticssnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchanalyticssnapshot',
            name='snapshot_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
