# Generated by Django 6.0.2 on 2026-02-06 14:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('students', '0003_lead_idx_lead_email_lead_idx_lead_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('sla_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('sla_status', models.CharField(choices=[('ON_TIME', 'On Time'), ('LATE', 'Late'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_branch', to='branches.branch')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='students.document')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Review',
                'verbose_name_plural': 'Document Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='idx_doc_review_status'), models.Index(fields=['reviewer'], name='idx_doc_review_reviewer')],
            },
        ),
        migrations.CreateModel(
            name='ReviewSLA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('PASSPORT', 'Passport'), ('NATIONAL_ID', 'National ID'), ('TRANSCRIPT', 'Academic Transcript'), ('CERTIFICATE', 'Certificate'), ('ENGLISH_TEST', 'English Test Score'), ('BANK_STATEMENT', 'Bank Statement'), ('SPONSOR_LETTER', 'Sponsor Letter'), ('SOP', 'Statement of Purpose'), ('CV', 'CV/Resume'), ('REFERENCE', 'Reference Letter'), ('OFFER_LETTER', 'Offer Letter'), ('CAS', 'CAS Document'), ('VISA', 'Visa Document'), ('OTHER', 'Other')], max_length=20)),
                ('target_hours', models.PositiveIntegerField(default=48)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_branch', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Review SLA',
                'verbose_name_plural': 'Review SLAs',
                'ordering': ['category'],
                'indexes': [models.Index(fields=['category'], name='idx_review_sla_category')],
            },
        ),
    ]
