from django.db import transaction
from rest_framework.exceptions import ValidationError
import datetime
from .models import Student, Lead

class StudentService:
    """
    Service layer for Student business logic.
    Decouples complex operations like Lead Conversion from ViewSets.
    """

    @staticmethod
    @transaction.atomic
    def convert_lead(lead: Lead, user):
        """
        Convert a Lead into a Student.
        Student code is auto-generated by pre_save signal.
        """
        if lead.status == Lead.Status.CONVERTED:
            raise ValidationError("Lead is already converted.")
            
        try:
            # Create Student
            # Note: student_code is NOT passed here, signal will handle it.
            student = Student.objects.create(
                lead=lead,
                branch=lead.branch,
                first_name=lead.first_name,
                last_name=lead.last_name,
                email=lead.email,
                phone=lead.phone,
                counselor=lead.assigned_to, # Inherit counselor from Lead
                source=lead.source,
                status=Student.Status.ACTIVE
            )
            
            # Update Lead status
            lead.status = Lead.Status.CONVERTED
            lead.save()
            
            return student

        except Exception as e:
            # Re-raise as ValidationError for standard API error handling
            raise ValidationError(f"Failed to convert lead: {str(e)}")
