# Generated by Django 6.0.2 on 2026-02-07 18:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('DOCUMENTATION', 'Documentation'), ('FINANCE', 'Finance'), ('ADMISSION', 'Admission'), ('VISA_PREP', 'Visa Prep'), ('POST_ARRIVAL', 'Post Arrival'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('DOCUMENTATION', 'Documentation'), ('FINANCE', 'Finance'), ('ADMISSION', 'Admission'), ('VISA_PREP', 'Visa Prep'), ('POST_ARRIVAL', 'Post Arrival'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('due_days_offset', models.IntegerField(default=7, help_text='Number of days from trigger to set the due date')),
                ('country', models.CharField(blank=True, help_text='Specific country this template applies to (or null for all)', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_branch', to='branches.branch')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
