# Generated by Django 6.0.2 on 2026-02-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_category_tasktemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='trigger_status',
            field=models.CharField(blank=True, help_text='Application status that triggers this task (e.g. SUBMITTED)', max_length=50, null=True),
        ),
    ]
