# Generated by Django 6.0.2 on 2026-02-08 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_assigned_to_application_fit_score_and_more'),
        ('tasks', '0003_tasktemplate_trigger_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='applications.application'),
        ),
    ]
