# Generated by Django 6.0.1 on 2026-02-04 17:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique document name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_uploadable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisaType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Student, Visit, Work', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination_country', models.CharField(choices=[('UK', 'United Kingdom'), ('USA', 'United States'), ('CANADA', 'Canada'), ('AUSTRALIA', 'Australia'), ('PAKISTAN', 'Pakistan'), ('INDIA', 'India'), ('GLOBAL', 'Global')], help_text='Where the student wants to go', max_length=50)),
                ('origin_country', models.CharField(blank=True, choices=[('UK', 'United Kingdom'), ('USA', 'United States'), ('CANADA', 'Canada'), ('AUSTRALIA', 'Australia'), ('PAKISTAN', 'Pakistan'), ('INDIA', 'India'), ('GLOBAL', 'Global')], help_text='Specific origin (e.g. Pakistan). Leave Empty for GLOBAL rule.', max_length=50, null=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_documents', models.ManyToManyField(related_name='rules', to='requirements.requireddocument')),
                ('visa_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='requirements.visatype')),
            ],
            options={
                'verbose_name': 'Visa Requirement Rule',
                'ordering': ['destination_country', 'origin_country'],
            },
        ),
    ]
