# Generated by Django 6.0.2 on 2026-02-06 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignstep',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_steps', to='messaging.messagetemplate'),
        ),
        migrations.AddField(
            model_name='campaignactivity',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaignstep'),
        ),
        migrations.AddIndex(
            model_name='campaignstep',
            index=models.Index(fields=['campaign', 'order'], name='idx_campaign_step_order'),
        ),
    ]
