# Generated by Django 6.0.2 on 2026-02-06 14:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('trigger', models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('STUDENT_CREATED', 'Student Created'), ('APPLICATION_STATUS_CHANGED', 'Application Status Changed'), ('VISA_STATUS_CHANGED', 'Visa Status Changed'), ('TASK_OVERDUE', 'Task Overdue'), ('DOCUMENT_UPLOADED', 'Document Uploaded')], max_length=40)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Conditions JSON for evaluation')),
                ('actions', models.JSONField(blank=True, default=list, help_text='Actions JSON (e.g. create task, send message)')),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_branch', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_rules_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='SUCCESS', max_length=10)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_branch', to='branches.branch')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='automation.automationrule')),
            ],
            options={
                'ordering': ['-ran_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskEscalationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='HIGH', max_length=10)),
                ('escalate_after_hours', models.PositiveIntegerField(default=24)),
                ('escalate_to_role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('COUNTRY_MANAGER', 'Country Manager'), ('BRANCH_MANAGER', 'Branch Manager'), ('COUNSELOR', 'Branch Counselor'), ('FINANCE_OFFICER', 'Finance Officer'), ('DOC_PROCESSOR', 'Document Processor'), ('AUDITOR', 'Read-Only Auditor')], default='BRANCH_MANAGER', max_length=20)),
                ('notify_channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('IN_APP', 'In-App')], default='IN_APP', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_branch', to='branches.branch')),
            ],
            options={
                'ordering': ['priority', 'escalate_after_hours'],
            },
        ),
    ]
