# Generated by Django 6.0.1 on 2026-02-04 17:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(choices=[('UK', 'United Kingdom'), ('USA', 'United States'), ('CANADA', 'Canada'), ('AUSTRALIA', 'Australia'), ('IRELAND', 'Ireland'), ('NEW_ZEALAND', 'New Zealand'), ('GERMANY', 'Germany'), ('NETHERLANDS', 'Netherlands'), ('FRANCE', 'France'), ('SWITZERLAND', 'Switzerland'), ('OTHER', 'Other')], default='UK', max_length=20)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='universities/logos/')),
                ('is_partner', models.BooleanField(default=False, help_text='Is this a partner university?')),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Commission Percentage (e.g. 10.0)', max_digits=5, null=True)),
                ('invoice_template', models.CharField(choices=[('STANDARD', 'Standard Invoice'), ('DETAILED', 'Detailed Invoice')], default='STANDARD', help_text='Template for generating commission claims', max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_branch', to='branches.branch')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g., MSc Data Science', max_length=255)),
                ('level', models.CharField(choices=[('FOUNDATION', 'Foundation'), ('UG', 'Undergraduate (Bachelor)'), ('PG', 'Postgraduate (Master)'), ('PHD', 'Doctorate (PhD)'), ('PRE_MASTERS', 'Pre-Masters'), ('DIPLOMA', 'Diploma')], max_length=15)),
                ('duration', models.CharField(help_text='e.g., 1 Year, 2 Years', max_length=50)),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('GBP', 'British Pound (£)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar')], default='GBP', max_length=3)),
                ('intakes', models.CharField(blank=True, help_text='e.g., Sep, Jan, May', max_length=100, null=True)),
                ('ielts_requirement', models.CharField(blank=True, help_text='e.g., 6.5 overall, 6.0 each', max_length=50, null=True)),
                ('academic_requirement', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_branch', to='branches.branch')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='universities.university')),
            ],
            options={
                'ordering': ['university', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionCriteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum academic score required (%)', max_digits=5, null=True)),
                ('min_ielts', models.DecimalField(blank=True, decimal_places=1, help_text='Overall IELTS score (e.g. 6.0)', max_digits=3, null=True)),
                ('gap_limit', models.PositiveIntegerField(default=2, help_text='Maximum acceptable study gap in years')),
                ('priority_rank', models.PositiveIntegerField(default=10, help_text='1 = High Priority/Partner, 10 = Low')),
                ('accepted_territories', models.TextField(default='Global', help_text='Territories accepted (e.g. Global, South Asia)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_branch', to='branches.branch')),
                ('university', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_criteria', to='universities.university')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
