# Generated by Django 6.0.1 on 2026-02-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissioncriteria',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='admissioncriteria',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='admissioncriteria',
            index=models.Index(fields=['branch', 'is_deleted'], name='admissioncriteria_branch_active_idx'),
        ),
        migrations.AddIndex(
            model_name='admissioncriteria',
            index=models.Index(fields=['branch', 'created_at'], name='admissioncriteria_branch_created_idx'),
        ),
    ]
