# Generated by Django 6.0.1 on 2026-02-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='admissioncriteria',
            name='admissioncriteria_branch_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='admissioncriteria',
            name='admissioncriteria_branch_created_idx',
        ),
    ]
