# Generated by Django 6.0.2 on 2026-02-06 19:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('universities', '0003_add_field_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage of Tuition'), ('FIXED', 'Fixed Amount')], default='PERCENTAGE', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='e.g. 10.00 for 10% or 5000.00 for £5k', max_digits=12)),
                ('min_cgpa', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum academic score required for this scholarship (%)', max_digits=5, null=True)),
                ('min_ielts', models.DecimalField(blank=True, decimal_places=1, help_text='Overall IELTS score required', max_digits=3, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_branch', to='branches.branch')),
                ('course', models.ForeignKey(blank=True, help_text='Optional: Link to a specific course', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='universities.course')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='universities.university')),
            ],
            options={
                'verbose_name': 'Scholarship',
                'verbose_name_plural': 'Scholarships',
                'ordering': ['-value'],
            },
        ),
    ]
