# Generated by Django 6.0.2 on 2026-02-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_intakedate_partnershipagreement_universitycontact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='territories',
            field=models.TextField(blank=True, help_text='Geographic territories covered by this partnership', null=True),
        ),
    ]
