# Generated by Django 6.0.2 on 2026-02-08 20:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_latitude_branch_longitude'),
        ('universities', '0006_add_territories_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='data_source',
            field=models.CharField(choices=[('MANUAL', 'Manual Entry'), ('PARTNER_PORTAL', 'Partner Portal'), ('OFFICIAL_WEBSITE', 'Official Website'), ('UCAS', 'UCAS'), ('EXCEL_IMPORT', 'Excel Import')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='deposit_required',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_months',
            field=models.IntegerField(blank=True, help_text='Duration in months', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='ielts_each_band',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='ielts_overall',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='intake_january',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='intake_may',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='intake_september',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_data_verified',
            field=models.BooleanField(default=False, help_text='Has this data been verified against official source?'),
        ),
        migrations.AddField(
            model_name='course',
            name='last_verified',
            field=models.DateTimeField(blank=True, help_text='When data was last verified', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='official_url',
            field=models.URLField(blank=True, help_text='Official course page URL', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='tuition_fee_home',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Home/UK student fee', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='work_experience_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='work_experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CourseRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(choices=[('PK', 'Pakistan'), ('BD', 'Bangladesh'), ('IN', 'India'), ('NG', 'Nigeria'), ('GH', 'Ghana'), ('KE', 'Kenya'), ('NP', 'Nepal'), ('LK', 'Sri Lanka'), ('AE', 'UAE'), ('SA', 'Saudi Arabia'), ('OTHER', 'Other Countries')], max_length=10)),
                ('min_qualification', models.CharField(help_text="e.g., 16 years education, Bachelor's degree", max_length=255)),
                ('accepted_qualifications', models.JSONField(blank=True, default=list, help_text='List of accepted qualifications')),
                ('min_gpa', models.DecimalField(blank=True, decimal_places=2, help_text='Min GPA on 4.0 scale', max_digits=3, null=True)),
                ('min_percentage', models.IntegerField(blank=True, help_text='Min percentage score', null=True)),
                ('min_cgpa', models.DecimalField(blank=True, decimal_places=2, help_text='Min CGPA on local scale', max_digits=3, null=True)),
                ('ielts_overall', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('ielts_speaking', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('ielts_writing', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('ielts_reading', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('ielts_listening', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('toefl_score', models.IntegerField(blank=True, null=True)),
                ('pte_score', models.IntegerField(blank=True, null=True)),
                ('duolingo_score', models.IntegerField(blank=True, null=True)),
                ('work_experience_years', models.IntegerField(default=0)),
                ('work_experience_required', models.BooleanField(default=False)),
                ('work_experience_details', models.TextField(blank=True, null=True)),
                ('required_documents', models.JSONField(blank=True, default=list)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('special_conditions', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_branch', to='branches.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_requirements', to='universities.course')),
            ],
            options={
                'ordering': ['course', 'country'],
                'unique_together': {('course', 'country')},
            },
        ),
    ]
