# Generated by Django 6.0.2 on 2026-02-09 06:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_latitude_branch_longitude'),
        ('universities', '0007_add_course_requirements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivingCostEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('monthly_rent', models.DecimalField(decimal_places=2, help_text='Average rent per month', max_digits=10)),
                ('monthly_food', models.DecimalField(decimal_places=2, help_text='Food and groceries per month', max_digits=10)),
                ('monthly_transport', models.DecimalField(decimal_places=2, help_text='Local transport per month', max_digits=10)),
                ('monthly_utilities', models.DecimalField(decimal_places=2, default=150, help_text='Bills, phone, internet', max_digits=10)),
                ('monthly_other', models.DecimalField(decimal_places=2, default=200, help_text='Entertainment, supplies, misc', max_digits=10)),
                ('visa_fee', models.DecimalField(decimal_places=2, default=490, help_text='Student visa fee', max_digits=10)),
                ('ihs_per_year', models.DecimalField(decimal_places=2, default=776, help_text='Immigration Health Surcharge/year', max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['country', 'city'],
                'unique_together': {('city', 'country')},
            },
        ),
        migrations.CreateModel(
            name='CourseWishlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this saved course', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_branch', to='branches.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='universities.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
