# Generated by Django 6.0.2 on 2026-02-09 06:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_applicationnote_application'),
        ('branches', '0003_branch_latitude_branch_longitude'),
        ('students', '0008_document_application_lead_suggested_universities'),
        ('universities', '0008_add_wishlist_and_living_costs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Data Scientist, Financial Analyst', max_length=200)),
                ('sector', models.CharField(choices=[('TECH', 'Technology'), ('FINANCE', 'Finance & Banking'), ('HEALTH', 'Healthcare'), ('ENGINEERING', 'Engineering'), ('CONSULTING', 'Consulting'), ('MARKETING', 'Marketing & Media'), ('EDUCATION', 'Education'), ('GOVERNMENT', 'Government & Public Sector'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('salary_min', models.IntegerField(blank=True, help_text='Entry level salary GBP', null=True)),
                ('salary_max', models.IntegerField(blank=True, help_text='Senior level salary GBP', null=True)),
                ('salary_median', models.IntegerField(blank=True, help_text='Median salary GBP', null=True)),
                ('employment_rate', models.IntegerField(blank=True, help_text='% employed in 6 months', null=True)),
                ('growth_outlook', models.CharField(choices=[('HIGH', 'High Growth'), ('MODERATE', 'Moderate'), ('STABLE', 'Stable'), ('DECLINING', 'Declining')], default='MODERATE', max_length=20)),
                ('key_skills', models.TextField(blank=True, help_text='Comma-separated skills', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='career_paths', to='universities.course')),
            ],
            options={
                'ordering': ['sector', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CourseQuickApply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('guest_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('guest_country', models.CharField(blank=True, max_length=50, null=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ielts_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('work_experience_years', models.IntegerField(default=0)),
                ('preferred_intake', models.CharField(blank=True, help_text='e.g., Sep 2025', max_length=20, null=True)),
                ('message', models.TextField(blank=True, help_text='Additional message', null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('CONVERTED', 'Converted to Application'), ('REJECTED', 'Not Interested')], default='NEW', max_length=20)),
                ('source', models.CharField(default='COURSE_FINDER', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_branch', to='branches.branch')),
                ('converted_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_apply_source', to='applications.application')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_applies', to='universities.course')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quick_applies', to='students.student')),
            ],
            options={
                'verbose_name': 'Quick Apply',
                'verbose_name_plural': 'Quick Applies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(help_text='1-5 star rating')),
                ('teaching_quality', models.IntegerField(blank=True, null=True)),
                ('career_prospects', models.IntegerField(blank=True, null=True)),
                ('value_for_money', models.IntegerField(blank=True, null=True)),
                ('course_content', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('pros', models.TextField(blank=True, help_text='What was good', null=True)),
                ('cons', models.TextField(blank=True, help_text='What could be improved', null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified student/alumni')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('helpful_count', models.IntegerField(default=0)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='universities.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('course', 'user')},
            },
        ),
    ]
